[theme]
primaryColor = "#d9a441"
backgroundColor = "#070604"
secondaryBackgroundColor = "#100c08"
textColor = "#eee8dc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
